# This is a basic workflow to help you get started with Actions

name: deploy-yolo3-docker

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - .github/workflows/deploy_yolo3_docker.yml
      - ./4_Deploy/*
  
  workflow_run:
    workflows: ["train-yolo3-job"]
    types: [completed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  Workspace: ML-Workspace
  RessourceGroup: MVPSession
  Modelname: yolov3

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_AE_CREDS }}
      - name: install azmlcli
        run: az extension add -n azure-cli-ml -y
      - name: attach to workspace
        run: az ml folder attach -w ${{ env.Workspace }} -g ${{ env.RessourceGroup }}
      - name: Download YoloV3 Custom Model from AML Model Registry
        run: |
             modelid=$(az ml model list --latest --model-name ${{ env.Modelname }} | jq -r .[].id)
             az ml model download --model-id $modelid --target-dir ./
             mv ./outputs/* ./Data/Model_Weights/
             ls -alH ./Data/Model_Weights/
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: totosan/ml-carsign:latest
