name: train-yolo3-job
on: 
  push:
    branches:
      - master
#  schedule:
#    - cron: "0 0/2 * * *"
#  pull_request:
#    branches:
#      - main
#    paths:
#      - workflows/train/tensorflow/mnist/**
#      - .github/workflows/train-tensorflow-mnist-job.yml
#      - requirements.txt
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with: 
        python-version: "3.7"
    - name: pip install
      run: pip install --upgrade -r aml-requirements.txt
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_AE_CREDS}}
    - name: install azmlcli
      run: az extension add -n azure-cli-ml -y
    - name: attach to workspace
      run: az ml folder attach -w ML-Workspace -g MVPSession
    - name: install conda
#    - uses: conda-incubator/setup-miniconda@v2
#      with:
#        activate-environment: yolo
#        environment-file: ./2_Training/environment.yml
#        python-version: 3.7
#        auto-activate-base: false
    - name: download general yolo v3
      run : python ./2_Training/Download_and_Convert_YOLO_weights.py
    - name: run workflow
      run: python ./2_Training/job.py
